version: '3.3'
services:
 mysql:
  image: mysql:latest
  container_name: 'mysql'
  volumes:
    - ./.docker/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
    - ./.docker/database/data.sql:/docker-entrypoint-initdb.d/2-data.sql:ro
  restart: always
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: 123
    MYSQL_ROOT_PASSWORD: bisu123!
    MYSQL_DATABASE: bisu
  ports:
    - 3306:3306