version: "3.5"
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=bisu-cluster
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - bisu
  kibana:
    image: kibana:7.4.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - bisu
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./.docker/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
      - ./.docker/database/data.sql:/docker-entrypoint-initdb.d/2-data.sql:ro
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: bisu123!
      MYSQL_DATABASE: bisu
    ports:
      - 3306:3306
    networks:
      - bisu
  api:
    restart: always
    image: api
    env_file:
      - ./bisu.env
    build:
      context: ./
      dockerfile: Infrastructure/Apps/Api/Dockerfile
    container_name: api
    hostname: api
    volumes:
      - ./:/usr/app/bisu:cached
      - /usr/app/bisu/node_modules/
      - ./Infrastructure/Apps/Api:/usr/app/bisu/Infrastructure/Apps/Api:cached
      - /usr/app/bisu/Infrastructure/Apps/Api/node_modules/
      - ./Core:/usr/app/bisu/Core:cached
      - /usr/app/bisu/Core/node_modules/
      - ./Infrastructure/Data:/usr/app/bisu/Infrastructure/Data:cached
      - /usr/app/bisu/Infrastructure/Data/node_modules/
    networks:
      - bisu
    ports:
      - 8081:8081
      - 9231:9231
    depends_on:
      - mysql
      - elasticsearch
      - kibana
  # ui:
  #   restart: always
  #   image: ui
  #   build:
  #     context: ./
  #     dockerfile: Infrastructure/Apps/UI/Dockerfile
  #   container_name: ui
  #   networks:
  #     - bisu
  #   ports:
  #     - 8080:80
networks:
  bisu:
    name: bisu-network
volumes:
  esdata:
    driver: local
